### ISSUE TITLE
【bug】主题预览链接显示有问题

### ISSUE THREAD

**Issue by kagol** [xitu/juejin-markdown-themes#118]
@lijinghust 
以下主题预览链接，显示undefined，控制台报错，没法预览：
[https://juejin-markdown-themes.netlify.app/](https://juejin-markdown-themes.netlify.app/)

显示undefined：
![image](https://user-images.githubusercontent.com/9566362/157579121-ea5291b3-f8f8-4783-89d3-9ea5f9cdf00f.png)

控制台报错：
![image](https://user-images.githubusercontent.com/9566362/157579053-112e4e2a-217b-434d-b453-5f329ad24cf8.png)

**Comment by Ali-ovo** [comment]
我也遇到了 这个咋解决啊 没办法了么

**Comment by xgqfrms** [comment]
# solution ✅

> read source code & find solution fix it

https://codepen.io/xgqfrms/full/JjMRqrQ

**Comment by kagol** [comment]
2022.4.25 更新，最新的主题预览链接已经好了，此issue关闭
