### ISSUE TITLE
想咨询个人如何使用这些主题呢

### ISSUE THREAD

**Issue by gujiwuqing** [xitu/juejin-markdown-themes#133]
你好，我想个人在项目中使用掘金富文本，以及使用这些主题，想咨询使用方法

**Comment by gujiwuqing** [comment]
> 你好，我想个人在项目中使用掘金富文本，以及使用这些主题，想咨询使用方法

准确说是如何使用这些主题

**Comment by linxsbox** [comment]
@gujiwuqing 
你好，此项目为掘金文档编辑器的开放能力。目前来说没有提供独立的开发包或者 npmjs 库，后续如何是否有这方面的意愿需要掘金官方回复。

如果只是使用相关的 markdown 主题的话，那么可以自行联系主题提供作者授权即可。
