### ISSUE TITLE
有坑！注意事项文档不详细！！

### ISSUE THREAD

**Issue by Popxie** [xitu/juejin-markdown-themes#74]
是这样子的，我看完了文档，按照文档死活都不生效。

到最后才发现：

```bash
---
# themes: juejin, github, smartblue, cyanosis, channing-cyan, fancy, hydrogen, condensed-night-purple, greenwillow, v-green, vue-pro, healer-readable, mk-cute, jzman, geek-black, awesome-green, qklhk-chocolate
theme: smartblue
highlight: vs2015
---
```

上面这行代码 有放到文章开头 第一行！前面不能有其他的东西（我是因为有注释头，当时没去掉导致一直不生效）

希望能把这个代码生效的前提必要条件声明一下呀~~

**Comment by itcodes** [comment]
好的。收到反馈。我们这块调整一下。

**Comment by Popxie** [comment]
> > 是这样子的，我看完了文档，按照文档死活都不生效。
> > 到最后才发现：
> > ```shell
> > ---
> > # themes: juejin, github, smartblue, cyanosis, channing-cyan, fancy, hydrogen, condensed-night-purple, greenwillow, v-green, vue-pro, healer-readable, mk-cute, jzman, geek-black, awesome-green, qklhk-chocolate
> > theme: smartblue
> > highlight: vs2015
> > ---
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 上面这行代码 有放到文章开头 第一行！前面不能有其他的东西（我是因为有注释头，当时没去掉导致一直不生效）
> > 希望能把这个代码生效的前提必要条件声明一下呀~~
> 
> 加一个 frontmatter 到 plugins 就生效了，可以过滤注释。
> 
> 但是我有个新问题，`theme：juejin ` 不生效，我直接`import 'juejin-markdown-themes/dist/juejin.css';`了

”加一个 frontmatter 到 plugins 就生效了，可以过滤注释“啥意思？ 加在哪里？没看明白，这个我就不清楚了诶 我就是顺路提个issue，问题也没这么麻烦 只要把掘金的主题代码放到头部 就没啥问题了😂
