### ISSUE TITLE
新主题发布后，没有效果

### ISSUE THREAD

**Issue by viewweiwu** [xitu/juejin-markdown-themes#78]
https://github.com/xitu/juejin-markdown-themes/pull/69

在在编辑时有效果

![image](https://user-images.githubusercontent.com/14287892/126416195-92c10342-177f-4115-9e68-b405dab93678.png)

发布后没有效果

![image](https://user-images.githubusercontent.com/14287892/126416249-32bac9f5-3a50-46c2-b4a2-d05f2e317c29.png)

**Comment by itcodes** [comment]
收到。文章页的主题版本号没有升级，下次上线顺带升级一下就可以。非常抱歉。

**Comment by viewweiwu** [comment]
这样子啊，如果可以的话，如果都会这样子的话，最好在贡献指南里提到这一点。🤣
